### ISSUE TITLE
Loopmail ALWAYS result in "Oops, session expired" Error, often with the entire content of the mail lost

### ISSUE THREAD

**Issue by Kevin-He-DVHS** [maheshmurag/InTheLoop#22]
## Expected Behavior
After sending any Loopmail, no error message is shown regarding session data being tampered.
## Actual behavior
In the Loop tampers session data, resulting in the error message accompanied with data loss. (sometimes)
## Remarks
This is a very _serious_ issue, because it can sometimes cause data loss when School Loop fails to save your message, but I believe that it will be very hard to fix without removing the ability to keep the user logged in in School Loop: it seems that with the "In the Loop" extension, the user is always kept logged in. The "Normal" School Loop automatically expire a session (log the user out) after a certain amount of time. This extension must have tampered the session resulting in this error.
## Suggested Workarounds
Add an extension option to disable the "keep logged in" feature.

**Comment by maheshmurag** [comment]
Hey Kevin, thanks for the The main functionality of In The Loop is in simply modifying the HTML and styling of the webpage, not in the changing the session data of the page. Are you using the notifications feature of the In The Loop? If so, could you try disabling the feature in the extension options and seeing if that affects the issue?

Unfortunately I no longer have access to a School Loop account to do testing, so it might be a bit hard to work on.
